# -*- coding: utf-8 -*-
"""
/***************************************************************************
 JapanBasemap
                                 A QGIS plugin
 指定されたベクタに交差(intersect)する範囲内で、指定した地図情報レベルの国土基本図図郭を生成します
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-06-18
        copyright            : (C) 2022 by Epoppo
        email                : poppo.circle@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = "Epoppo"
__date__ = "2022-06-18"
__copyright__ = "(C) 2022 by Epoppo"


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load JapanBasemap class from file JapanBasemap.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .japan_basemap import JapanBasemapPlugin

    return JapanBasemapPlugin()
