theme: jekyll-theme-cayman
description: 国土基本図図郭、地域メッシュを生成するQgis3用プラグイン
show_downloads: true
github:
  zip_url: https://github.com/Epoppo/JapanBasemap/releases/download/v2_0_0/japan_basemap_v2_0_0.zip
  another_url: v2.0.0
plugins:
  - jekyll-sitemap
